
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_artifacts:
    +enabled: false
  my_new_project:
    pre_hook: ["select 1"]
    # Applies to all files under models/example/
    example:
      materialized: view

vars:
  staging_prefixes: ['stg_']
  intermediate_prefixes: ['int_']
  marts_prefixes: ['fct_', 'dim_']
  other_prefixes: ['rpt_']
  dbt_artifacts_schema: "{{target.schema}}_meta"
  remove_from_res:
    node: 
      - config:
        - materialized
        - schema
      - alias

on-run-end: 
  # - "{{ on_end(table='load_results', schema='DBT_BPERIGAUD_AUDIT', database = 'DEVELOPMENT') }}"
  - "{{ on_end2(table='load_results', schema='DBT_BPERIGAUD_AUDIT', database = 'DEVELOPMENT', macro_transform_res_dict=example_transform_res_1) }}"
  # - "{{ dbt_artifacts.upload_results(results) }}"
  # - "{{ log_results(results) }}"

sources:
  dbt_artifacts:
    +schema: "xxxx"