# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jobs-as-code/main/src/schemas/load_job_schema.json

jobs:
  dev_job:
    account_id: 123
    project_id: 456
    environment_id: 789
    name: My test job
    settings: 
      threads: 4
      target_name: default
    run_generate_sources: false
    execute_steps: 
      - dbt run
    generate_docs: false
    schedule: 
       cron: ""
    triggers: 
      schedule: false
    job_type: ci